version: "3.3"

services:
  rstudio:
    build: ./docker/images/r
    environment:
      - DISABLE_AUTH=TRUE
    image: "rocker/tidyverse:latest"
    volumes:
      - $PWD/lab:/lab
    container_name: rstudio
    ports:
      - 8787:8787
  database:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  jupyter:
    container_name: jupiter
    build: ./docker/images/jupyter
    volumes:
      - $PWD/lab:/lab
    environment:
      - PASSWORD=baki93
      - JUPYTER_TOKEN=easy
    ports:
      - 8888:8888
